fixup! ASoC: SOF: Intel: hda: add new flags for DAI_CONFIG
The DAI config->flags is an u8 type, which on some architectures leads
to link issues such as

ERROR: modpost: "__bad_cmpxchg" [sound/soc/sof/snd-sof.ko] undefined!
ERROR: modpost: "__bad_cmpxchg" [sound/soc/sof/intel/snd-sof-intel-hda-common.ko] undefined!

This is root-caused to the use of set_mask_bits(), which is completely
overkill here. We don't need any sort of atomicity, just set a bit
before sending an IPC.

The implementation of set_mask_bits() should really detect that the
data type is not supported, but that's a separate story. We can use a
simpler macro instead.

Reported-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>