Merr: wm8958: Override the Rate, from the pdata
BZ: 139640

During VOIP call on Merr PR2 devices, the audio is robotic due the
codec being configured at different rate than 48k.

Since SSP is configured at 48k, the codec driver needs to override the
rate setting during hw_params.

Fixed compilation error: using pdata cached in mfd driver

Ported from K3.4 BZ: 129506

Orig-Change-Id: I7d80701ba59768af52b86eb8859adf5b9b6c1233
Signed-off-by: Samreen Nilofer <samreen.nilofer@intel.com>
Reviewed-on: http://android.intel.com:8080/128942
Reviewed-by: B, Jayachandran <jayachandran.b@intel.com>
Reviewed-by: Kp, Jeeja <jeeja.kp@intel.com>
Reviewed-by: Babu, Ramesh <ramesh.babu@intel.com>
Reviewed-by: Abdullah, Omair M <omair.m.abdullah@intel.com>
Reviewed-by: Koul, Vinod <vinod.koul@intel.com>
Reviewed-by: Yang, Fei <fei.yang@intel.com>
Tested-by: Gupta, ArvindX K <arvindx.k.gupta@intel.com>
Reviewed-by: cactus <cactus@intel.com>
Tested-by: cactus <cactus@intel.com>
(cherry picked from commit 0c7f8ac7c2693e18585e85214d278cb50d26396f)

Conflicts:

	include/linux/mfd/wm8994/pdata.h

Orig-Change-Id: I1c659265488cf52aa9a5a8fd7ff183b92f2a3ad3
Signed-off-by: Subhransu S. Prusty <subhransu.s.prusty@intel.com>
Reviewed-on: http://android.intel.com:8080/133337
Reviewed-by: Shah, Hardik T <hardik.t.shah@intel.com>
Reviewed-by: Koul, Vinod <vinod.koul@intel.com>
Reviewed-by: Yang, Fei <fei.yang@intel.com>
Tested-by: Koyili, SrikanthX <srikanthx.koyili@intel.com>
Reviewed-by: cactus <cactus@intel.com>
Tested-by: cactus <cactus@intel.com>

Conflicts:

	arch/x86/platform/intel-mid/device_libs/platform_wm8994.c

Change-Id: I8b0416940715108a5bc2f7810a92126ae4d101a3
Signed-off-by: Dharageswari.R <dharageswari.r@intel.com>
Reviewed-on: https://android.intel.com/217132
Reviewed-by: Koul, Vinod <vinod.koul@intel.com>
Tested-by: Koul, Vinod <vinod.koul@intel.com>