ASoC: SOF: Intel: hda-dsp: fix cross-compilation issue
NOT FOR UPSTREAM as is. This needs to be squashed with ("ASoC: SOF:
Intel: hda: Allow trace DMA in S0 when DSP is in D0I3 for debug")

Kbuild reports error with module handling:

  CC [M]  sound/soc/sof/intel/hda-dsp.o
sound/soc/sof/intel/hda-dsp.c:27:68: error: expected ')' before 'bool'

 module_param_named(enable_trace_D0I3_S0, hda_enable_trace_D0I3_S0,
 bool, 0444);
                                                                     ^
sound/soc/sof/intel/hda-dsp.c:29:4: error: expected ')' before string constant
    "SOF HDA enable trace when the DSP is in D0I3 in S0");
    ^

Fix by including linux/module.h

Cc: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>