fixup! ASoC: SOF: Drop 'header' parameter from tx_message() API
ERROR: space required after that ',' (ctx:VxO)
+		ret = sof_ipc_tx_message(sdev->ipc,&stream, sizeof(stream),
 		                                  ^

ERROR: space required before that '&' (ctx:OxV)
+		ret = sof_ipc_tx_message(sdev->ipc,&stream, sizeof(stream),
 		                                   ^

total: 2 errors, 0 warnings, 0 checks, 292 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

"[PATCH] ASoC: SOF: Drop 'header' parameter from tx_message() API" has style problems, please review.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>