ASoC: SOF: Intel: hda-dsp: fix compilation warning
sound/soc/sof/intel/hda-dsp.c: In function
‘hda_dsp_set_hw_params_upon_resume’:
sound/soc/sof/intel/hda-dsp.c:469:6: error: variable ‘stream_tag’ set
but not used [-Werror=unused-but-set-variable]
  int stream_tag;

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>